
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 24 02:10:10 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 20;
  public static final int PAREN_LEFT = 7;
  public static final int READ = 9;
  public static final int CURLY_PAREN_RIGHT = 4;
  public static final int CONST_NUM = 27;
  public static final int SEMICOLON = 21;
  public static final int PLUS = 16;
  public static final int GOTO = 11;
  public static final int SQUARE_PAREN_LEFT = 5;
  public static final int PLUS_PLUS = 14;
  public static final int IDENTIFIER = 26;
  public static final int COLON = 22;
  public static final int PROGRAM = 2;
  public static final int EQUALS = 13;
  public static final int COMMA = 23;
  public static final int EOF = 0;
  public static final int CONST_BOOL = 28;
  public static final int DIV = 19;
  public static final int PAREN_RIGHT = 8;
  public static final int SQUARE_PAREN_RIGHT = 6;
  public static final int CURLY_PAREN_LEFT = 3;
  public static final int MINUS = 17;
  public static final int CONST = 24;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int NEW = 12;
  public static final int MINUS_MINUS = 15;
  public static final int VOID = 25;
  public static final int MUL = 18;
  public static final int CONST_CHAR = 29;
}

